DROP TABLE IF EXISTS cliente;
DROP TABLE IF EXISTS usuario;

CREATE TABLE usuario(
	id INT IDENTITY PRIMARY KEY,
	name NVARCHAR(MAX) NOT NULL,
	email VARCHAR(300) NOT NULL
);

CREATE TABLE cliente(
	id INT IDENTITY PRIMARY KEY,
	user_id INT NOT NULL,

	name NVARCHAR(MAX) NOT NULL,
	created_at DATETIME NOT NULL DEFAULT GETDATE(),

	FOREIGN KEY (user_id)
		REFERENCES usuario(id)
		ON DELETE CASCADE
);